### ISSUE TITLE
OTP with UK number not working

### ISSUE THREAD

**Issue by MomoCrafter2013** [rvaidun/befake#124] opened 2023-05-28 16:23 UTC
When I try to log in with the OTP sent to my phone this appears: Error: INVALID_SESSION_INFO

I've tried with many OTPs and none of them work.

Thanks

**Comment by Ein-Tim** [comment] 2023-05-28 16:27
Duplicate of #116

**Comment by MomoCrafter2013** [comment] 2023-05-28 16:32
> Duplicate of #116

It's not, I was getting the prompt to put the code but it didn't work.

But nevermind, I solved it

**Comment by MomoCrafter2013** [comment] 2023-05-28 16:36
> In this case you might want to share your solution here, for other people who may also encounter this problem, and close this issue.

I was using an old link apparently, I had to use this one https://befake-623af.web.app/

**Closed** 2023-05-28 16:36 UTC
